development:
  adapter: async
  url: 'redis://127.0.0.1/0' 

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("redis://127.0.0.1") { "redis://localhost:6379/1" } %>
  channel_prefix: social_media_production
